export const recipes = [
  {
    imgSrc: "/imgs/recipe-1.jpg",
    title: "Indonesische vegan rendang",
    description: "op kruidige parelcouscous",
    duration: "10 minutes",
    weight: "240g",
    quantity: "1",
  },
  {
    imgSrc: "/imgs/recipe-2.jpg",
    title: "Cajungarnalen in tomaten saus",
    description: "met appel, spinazie en jasmijnrijst",
    duration: "10 minutes",
    weight: "180g",
    quantity: "2",
  },
  {
    imgSrc: "/imgs/recipe-3.jpg",
    title: "Biefstuk met herfstige ovengroente",
    description: "met kokus-kurkumarijs en rodekoolsalade",
    duration: "12 minutes",
    weight: "240g",
    quantity: "1",
  },
  {
    imgSrc: "/imgs/recipe-4.jpg",
    title: "Japanse Kipcurry",
    description: "met kazige aardappelpuree",
    duration: "12 minutes",
    weight: "240g",
    quantity: "2",
  },
  {
    imgSrc: "/imgs/recipe-5.jpg",
    title: "Cajungarnalen in tomaten saus",
    description: "met kazige aardappelpuree",
    duration: "12 minutes",
    weight: "240g",
    quantity: "2",
  },
  {
    imgSrc: "/imgs/recipe-6.jpg",
    title: "Biefstuk met herfstige ovengroente",
    description: "op kruidige parelcouscous",
    duration: "10 minutes",
    weight: "240g",
    quantity: "1",
  },
  {
    imgSrc: "/imgs/recipe-7.jpg",
    title: "Quinoasalade met gebraden kip",
    description: "met paprika en limoen-chipotledressing",
    duration: "12 minutes",
    weight: "240g",
    quantity: "1",
  },
  {
    imgSrc: "/imgs/recipe-8.jpg",
    title: "Bio-kip tandoori met ovengroente",
    description: "en een frisse yoghurt-korianderdip",
    duration: "10 minutes",
    weight: "240g",
    quantity: "2",
  },
];
